force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Context_Id__c.field-meta.xml
<CustomField>
    <fullName>Context_Id__c</fullName>
    <description>A Salesforce Id of any Salesforce record to tie this meeting to.</description>
    <externalId>true</externalId>
    <inlineHelpText>A Salesforce Id of any Salesforce record to tie this meeting to.</inlineHelpText>
    <label>Context Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeetingLookupTriggerHandler.cls
public without sharing class MeetingLookupTriggerHandler {

	public static void resolveLookup(List<SObject> objs) {
		List<Meeting__c> meetings = (List<Meeting__c>)objs;
		Map<SObjectType, SObjectField> refFields = getMeetingReferenceFields();	
		for (Meeting__c meeting : meetings) {
			if (meeting.Context_Id__c != null && meeting.Context_Id__c instanceof Id) {
				SObjectType sType = ((Id) meeting.Context_Id__c).getSObjectType();
				SObjectField field = refFields.get(sType);
				if (field != null) {
					meeting.put(field, meeting.Context_Id__c);
				}
			}
		}
	}

	private static Map<SObjectType, SObjectField> getMeetingReferenceFields() {
		Map<SObjectType, SObjectField> refFields = new Map<SObjectType, SObjectField>();
		for (SObjectField field : MEETING_FIELDS) {
			DescribeFieldResult dfr = field.getDescribe();
			if (dfr.getType() == Schema.DisplayType.REFERENCE && !dfr.getReferenceTo().isEmpty()) {
				refFields.put(dfr.getReferenceTo()[0], field);
			}
		}
		return refFields;

	}

	private static List<SObjectField> MEETING_FIELDS = 
		SObjectType.Meeting__c.fields.getMap().values();
}